WebUSB: On serial connection check baud rate before setting it.
microbit-foundation/python-editor-v3 pull request #1103
Opened 2023-02-17 18:38 UTC by microbit-carlos

Setting the baud rate makes DAPLink send a "break signal", which basically resets the target.

This is noticeable to the Python Editor users when switching tabs as it makes their programme reset.

We can avoid this reset by checking first the DAPLink serial settings and only set the baud rate if neccesary.

I tried to replicate the `Bad response for 8 -> 17` issue for about 5 minutes changing tabs and refreshing-and-reconnecting and it seems fine (and also checked that it's really easy to replicate in the Python Editor v2).
- https://github.com/microbit-foundation/python-editor-v3/issues/89

2023-02-24 12:10 UTC, microbit-robert requested changes
This looks good to me. Tested with v1, v2.00, and v2.21, and  the program no longer resets on switching tabs. Some minor changes requested via comments.

2023-02-24 12:10 UTC, microbit-robert commented on src/device/dap-wrapper.ts
> +    if (currentBaud != 115200) {
Please use JavaScript's strict equality operator.
```suggestion
    if (currentBaud !== 115200) {
```

2023-02-24 12:10 UTC, microbit-robert commented on src/device/dap-wrapper.ts
> +    const currentBaud = await this.daplink.getSerialBaudrate();
Please could you add a comment to summarize the required change here?

2023-02-27 17:23 UTC, microbit-robert commented on src/device/dap-wrapper.ts
> +      await this.daplink.setSerialBaudrate(115200);
Looks good, thanks.

2023-02-27 17:27 UTC, microbit-carlos commented
Awesome, thanks @microbit-robert!
I've left the GitHub web interface commits assuming this PR will be squashed when merged, but let me know if you prefer the branch to be squashed beforehand instead.

2023-02-27 17:27 UTC, microbit-carlos commented
Ah, it needs to be rebased anyway, I'll do that

2023-02-27 17:32 UTC, microbit-carlos commented
Okay, should be ready for merge now 👍

2023-02-27 17:33 UTC, merged

2023-03-03 11:57 UTC, microbit-matt-hillsdon commented
Now we've done this it might be worth trying to avoid resetting the serial console (i.e clearing scrollback) in this scenario as that's what most folks have been complaining about. Needs some thought though as serial output that doesn't match the running program is confusing (e.g. we might show a clickable traceback for it).